# Generated by Django 5.2.3 on 2025-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recepie",
            name="recepie_image",
            field=models.ImageField(upload_to="recepie/"),
        ),
    ]
